### ISSUE TITLE
Add build-system requirement to documentation.

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluonts#113]
See #74

Some of our dependencies might need to be installed locally. This can cause `pip install gluonts` to fail, since not all dependencies were installed successfully.

We should make this point clear in the docs.

Alternatively, we could think about making `ujson` (which caused most troubles) optional or offer docker-images which have gluon-ts already installed.

**Comment by lostella** [comment]
@jaheba anything to do here? otherwise we could close

**Comment by oby1** [comment]
`ujson` [added](https://github.com/ultrajson/ultrajson/releases/tag/3.0.0) wheels to [pypi](https://pypi.org/project/ujson/3.0.0/#files) in version `3.0.0`.  Simply upgrading the `ujson` dependency to a version >3 or even just loosening the constraint to allow for versions >3 will make installation faster and simpler on most platforms.

What's more, with [stricter dependency resolution](https://pip.pypa.io/en/latest/user_guide/#deprecation-timeline) coming to `pip` in 2021, it will no longer be possible to install a `ujson` version >3 along with gluonts.  Happy to open a separate issue or PR for the upgrade if it would be helpful.

**Comment by jaheba** [comment]
Thanks for pointing this out @oby1.

I was thinking about removing the dependency on `ujson` all-together, and make it optional. See #1188.

What do you think?

**Comment by oby1** [comment]
Looks great, nicely done!
