### ISSUE TITLE
Add IQN probabilistic head to the repo

### ISSUE THREAD

**Issue by adelegouttes** [awslabs/gluonts#1643]
## Description
After a discussion I had with @jgasthaus and @kashif at the ICML Time Series workshop, I would like to add the code we used for our IQN-RNN model. It is a general probabilistic method, using Implicit Quantile Network as a distribution output. On our preliminary results, it yields competitive KPIs against SQF-RNN. It would be great if you could evaluate it on your side, once it is merged. The code already exists as a part of `pytorch-ts` and is `torch` based. It works with `gluonts` backend already.

## Reference
- Paper: https://arxiv.org/pdf/2107.03743.pdf
- Pytorch-ts demo notebook: https://github.com/zalandoresearch/pytorch-ts/blob/master/examples/Implicit-Quantile-Network-Example.ipynb

**Comment by StatMixedML** [comment]
@adelegouttes Nice paper! Would be great to have the IQN available in gluonts!
