### ISSUE TITLE
GluonTS M4 benchmark code produces M4 results inferior to M4 competition results

### ISSUE THREAD

**Issue by gjmulder** [awslabs/gluonts#376]
I'm smoke testing your `./gluon-ts/examples/benchmark_m4.py` on some GPUs, and looking at the point forecasts for the different frequencies. Here's some sample results from the Monthly M4 data, with comparisons to both the statistical benchmarks and the two top M4 Competition entrants:

  |   | sMAPE | MASE
-- | -- | -- | --
benchmark | seasonal_naive | 15.256 | 1.205
  | naive | 15.988 | 1.260
  | naive2 | 14.427 | 1.063
  | ses | 13.618 | 1.020
  | holt | 14.828 | 1.010
  | theta_classic | 13.473 | 0.972
  | holt_damped | 13.003 | 0.970
  | combined | 13.434 | 0.966
  |   |   |  
GluonTS | DeepAREstimator | 14.067 | 1.145
  | MQCNNEstimator | 14.444 | 1.173
  |   |   |  
Smyl | Slawek | 12.126 | 0.884
Montero-Manso | Pablo | 12.639 | 0.893

I seem to remember @rshyamsundar  mentioning in the ISF workshop in Thessaloniki that the GluonTS results were competitive with the M4 entrants but, assuming I'm performing an apples-to-apples comparison, `benchmark_m4.py` doesn't seem to be @rshyamsundar  was referring to. If so, would you have any tuning / config / methodology suggestions for producing better results with GluonTS?

**Comment by tm1611** [comment]
Hi, I was also wondering how competitive the DeepAR algorithm is vs. the M4 methods as well as how more recent methods such as DeepState and DeepFactor perform in comparison. So here a few points: 

I played around with the algorithm and data and found that for example increasing the number of epochs or num_batches_per_epoch parameter increases the performance of DeepAR considerably. M4_monthly consists of 48,000 series so it seems the algorithm needs to "see" a little bit more data.  For your example of the m4_monthly data (num_batches_per_epoch=200) that leads to MASE of 0.9972 and sMAPE of 13.556 which is still far away from Smyl and Montero-Manso. 

In [1] you can find an aggregated accuracy of DeepAR on the entire M4 data (MASE=1.500, sMAPE=0.1192) vs Smyl (MASE=1.54, sMAPE=0.1137) and it states that "Its accuracy is close to the winning solution in the M4 competition" using default hyper-parameters so this may be the source of the competitiveness claim. However, there is also a built-in DeepAR algorithm in AWS SageMaker that, according to the gluonts.model.deepar documentation, "is unrelated to the implementation behind [SageMaker]". From the paper it is not clear to me whether the gluonts.model.deepar implementation or the SageMaker implementation was used. 

For comparison, according to my own calculations the automatic exponential smoothing function (ETS) of the R forecast package yields a sMAPE of 13.5356 and MASE of 0.945. The automatic ARIMA function yields similar results and simply averaging both methods works even better (sMAPE=12.9769, MASE=0.9092) for m4_monthly data. Results are calculated on my own and not validated (just saying as I am a little skeptical on the performance of this simple ETSARIMA approach). I know that DeepAR is not conceptualized for such a heterogeneous dataset as the M4 data which seems to be a possible explanation. 

My specifications for DeepAR on m4_monthly: {mx.random.seed(42), num_batches_per_epoch=200} and using the defaults for other hyperparameters. Moreover, neither DeepFactor nor DeepState seem to be close to being competitive on the M4 data using their defaults. It would be nice to know why this is the case and possible adjustments on their specifications.

Lastly, stability of results is definitely an issue as running the same model twice without seed yields highly variable results. Hope this was helpful.

[1] T. Januschowski, J. Gasthaus, Y. Wang et al., Criteria for classifying forecasting methods. International Journal of Forecasting (2019)

**Comment by gjmulder** [comment]
I've recently performed some GPU-based hyper-parameter optimisation on a modified M4 Daily data set:

- Added a static categorical for the domain (Demographic, Finance, Industry, Macro, Micro, Other)
- Added a static categorical indexing the individual time series (as per #410)

Next, there is an open issue #336 for running DeepState models on GPU, so I've focused my search on DeepAR models. My latest DeepAR hyper-parameters are:
 
- "batch_size" : 32,
- "dropout_rate" : 0.088,
-  "learning_rate" : 0.0063,
- "learning_rate_decay_factor" : 0.41,
- "max_epochs" : 60000, 
- "minimum_learning_rate" : 0.0000083,
- "num_batches_per_epoch" : 60,
- "num_cells" : 100,
- "num_layers" : 4,
- "weight_decay" : 1.7e-8,
- "patience" : 50,

And the results found at epoch 59558 were:
- 'MASE': 3.218
- 'sMAPE': 3.035

While better than the M4 Competition overall winning entries, this is extremely close to the result from the statistical methods, so a lot of GPU cycles spent for no appreciable gain :-)

**Comment by tm1611** [comment]
Thank you very much @gjmulder , I am looking forward to additional results from your side and would like to help in contributing some more results on the M4 data if help is wanted. 

So far, the best results that I got was an MASE of 3.3355 (including seeds=44 in m4_benchmark.py, epochs=200, num_batches_per_epoch=200, defaults for everything else) on the m4_daily.

Unfortunately, I could not replicate your results because I run into two problems and would be highly interested in your knowledge regarding 

1) How you included two static categorical variables in the algorithms and 
2) how you implemented HPO with gluonTS?

It would be nice if you'd be willing to share some of your knowledge, provide example code / an example script or something like that. 

Also, the m4_daily are dominated by data of the "finance" domain  (37% of the daily data are from this area) for which naive methods, such as the Naive2, work suprisingly well (multiplicative decomposition seems to work well on data with high ACF1). Hence, it may be interesting to compare the m4_daily by subsets (for example finance vs. non-finance) against benchmarks and other m4 methods. 

Thanks a lot.

**Comment by gjmulder** [comment]
The m4_daily look to be hard to forecast using ML methods. In contrast, the m4_hourly seems to be extremely challenging for the structural/statistical methods, perhaps due to multiple seasonality (24 hour and 7 day).

Here's the R script that I'm using to (re)generate the JSON M4 data. It assumes the metadata and directory structure in ~/.mxnet already exists and the M4-info.csv file  (https://github.com/M4Competition/M4-methods/blob/master/Dataset/M4-info.csv) is present in the current dir. There's a bit of date logic I needed to implement to deduce valid start dates as M4-ifo.csv is full of Y2K bugs (!!):

[split_M4_training.R.txt](https://github.com/awslabs/gluon-ts/files/3855558/split_M4_training.R.txt)

Note that the split code runs in two modes. "M4 competition" mode where it splits the M4 competition data. And "final" mode where it uses the complete post-competition data set. It is incorrect to compare accuracies with the M4 competition winners using the full data set, especially if you're building 100's of models, as I am.

The idea is that the categorical index of the individual TS is useful for local fitting, while the domain category of the TS might help global/meta-learning as per Smyl's winning approach. Getting start_dates correct ensures that the time series are aligned optimally for the lags GluonTS automatically generates based on the frequency of the time series.
  
My HPO code is a bit in flux. I'll have a useful self-contained and stable example soonish. I'm using HyperOpt (https://github.com/hyperopt/hyperopt) which in turn uses MongoDB to orchestrate the HPO. I kick off multiple jobs across a farm of GPUs and HyperOpt pulls model candidate designs from MongoDB and writes back their results. It is great - I can sit there running MongoDB queries and  get real-time results and trends on my HPO search.

**Comment by lixixibj** [comment]
> I'm smoke testing your `./gluon-ts/examples/benchmark_m4.py` on some GPUs, and looking at the point forecasts for the different frequencies. Here's some sample results from the Monthly M4 data, with comparisons to both the statistical benchmarks and the two top M4 Competition entrants:
> 
>  	 	sMAPE	MASE
> benchmark	seasonal_naive	15.256	1.205
>  	naive	15.988	1.260
>  	naive2	14.427	1.063
>  	ses	13.618	1.020
>  	holt	14.828	1.010
>  	theta_classic	13.473	0.972
>  	holt_damped	13.003	0.970
>  	combined	13.434	0.966
>  	 	 	 
> GluonTS	DeepAREstimator	14.067	1.145
>  	MQCNNEstimator	14.444	1.173
>  	 	 	 
> Smyl	Slawek	12.126	0.884
> Montero-Manso	Pablo	12.639	0.893
> I seem to remember @rshyamsundar mentioning in the ISF workshop in Thessaloniki that the GluonTS results were competitive with the M4 entrants but, assuming I'm performing an apples-to-apples comparison, `benchmark_m4.py` doesn't seem to be @rshyamsundar was referring to. If so, would you have any tuning / config / methodology suggestions for producing better results with GluonTS?

Hi, did you try methods in gluon-ts on other datasets of M4 competition? Could you please post the forecasting accuracy of other datasets online?  I want to compare my new method with gluon-ts on M4 datasets. Thanks a lot.

**Comment by tm1611** [comment]
@gjmulder 

Thanks again for your contribution and I am looking forward to more from your side. A few related notes (if not otherwise mentioned, I am refering to DeepAR):

### 1. Regarding your R script: 

I have slightly modified your script so it only uses the last 300 observations for yearly data. This is similarly to how yearly data are handled in gluonts to make numpy happy https://github.com/awslabs/gluon-ts/blob/481fc5fdd09abad012cf6398e06bc6be8b1de197/src/gluonts/dataset/repository/_m4.py#L60 

Easy fix in R: 
```r
if (length(target) >= 300){
    target <- xts::last(target, 300)
}
```

Also, I incorporated the possibility to opt for the same gluonts mock start date so `true_dates` vs. `mock date` can be compared.
 
```r
#
  if (true_dates == FALSE){
    start <- "1750-01-01 00:00:00"
  } else {
    start <- paste0(as.character(as.Date(time(train))[1]), " 00:00:00") 
  }
```

### 2.  `true_dates` vs. `mock_date` ("1750-01-01 00:00:00"). 

Referring to: 

> Getting start_dates correct ensures that the time series are aligned optimally for the lags GluonTS automatically generates based on the frequency of the time series.

- Experiment 1: m4_yearly_true_dates vs. m4_yearly (mock dates) 
- Experiment 2: m4_quarterly_true_dates vs. m4_quarterly (mock dates)
- Experiment 3: m4_monthly_true_dates vs. m4_monthly (mock dates)

Simple t-test on the means of MASE/sMAPE indicates that there is no difference between accuracy of using true dates vs mock dates, c.p., and based on twenty trials per experiment (10 vs. 10) given default hyperparameters. This is consistent across all three tested frequencies. 


### 3. Categorical index and domain category. 

> The idea is that the categorical index of the individual TS is useful for local fitting, while the domain category of the TS might help global/meta-learning as per Smyl's winning approach. 

Incorporating time series id as a static categorical features seems to clearly improve the accuracy. 

Including the domain category as a static categorical feature seems to slightly improve accuracy. 

However, I don't know how to include both static features at the same time, i.e. I have the data in the following form as `m4_weekly` with domain: 

```json
{"start":"1750-01-01
00:00:00", "target":[1089.2,1078.91,1079.88,1063.58,1060.61, 
...
36565.18,36565.18,35397.16],"feat_static_cat":[1,6]}
```

Simply using these data as before with  `use_feat_static_cat=True`  yields the following error message: 

```
INFO:root:using dataset already processed in path C:\Users\TM\.mxnet\gluon-ts\datasets\m4_weekly_domain.
INFO:root:Start model training
INFO:root:Epoch[0] Learning rate is 0.001
  0%|          | 0/100 [00:00<?, ?it/s]

infer_shape error. Arguments:
  data0: (32, 2)
  data1: (32, 1)
  data2: (32, 170, 3)
  data3: (32, 170)
  data4: (32, 170)
  data5: (32, 13, 3)
  data6: (32, 13)
  data7: (32, 13)

  0%|          | 0/100 [00:00<?, ?it/s]

---------------------------------------------------------------------------
DeferredInitializationError               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in _call_cached_op(self, *args)
    802             cargs = [args[i] if is_arg else i.data()
--> 803                      for is_arg, i in self._cached_op_args]
    804         except DeferredInitializationError:

~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in <listcomp>(.0)
    802             cargs = [args[i] if is_arg else i.data()
--> 803                      for is_arg, i in self._cached_op_args]
    804         except DeferredInitializationError:

~\Anaconda3\lib\site-packages\mxnet\gluon\parameter.py in data(self, ctx)
    493                                "instead." % (self.name, str(ctx), self._stype))
--> 494         return self._check_and_get(self._data, ctx)
    495 

~\Anaconda3\lib\site-packages\mxnet\gluon\parameter.py in _check_and_get(self, arr_list, ctx)
    207                 "You can also avoid deferred initialization by specifying in_units, " \
--> 208                 "num_features, etc., for network layers."%(self.name))
    209         raise RuntimeError(

DeferredInitializationError: Parameter 'deepartrainingnetwork0_lstm0_i2h_weight' has not been initialized yet because initialization was deferred. Actual initialization happens during the first forward pass. Please pass one batch of data through the network before accessing Parameters. You can also avoid deferred initialization by specifying in_units, num_features, etc., for network layers.

During handling of the above exception, another exception occurred:

MXNetError                                Traceback (most recent call last)
~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in _deferred_infer_shape(self, *args)
    788         try:
--> 789             self.infer_shape(*args)
    790         except Exception as e:

~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in infer_shape(self, *args)
    861         """Infers shape of Parameters from inputs."""
--> 862         self._infer_attrs('infer_shape', 'shape', *args)
    863 

~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in _infer_attrs(self, infer_fn, attr, *args)
    850             arg_attrs, _, aux_attrs = getattr(out, infer_fn)(
--> 851                 **{i.name: getattr(j, attr) for i, j in zip(inputs, args)})
    852             if arg_attrs is None:

~\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py in infer_shape(self, *args, **kwargs)
    995         try:
--> 996             res = self._infer_shape_impl(False, *args, **kwargs)
    997             if res[1] is None:

~\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py in _infer_shape_impl(self, partial, *args, **kwargs)
   1125             ctypes.byref(aux_shape_data),
-> 1126             ctypes.byref(complete)))
   1127         if complete.value != 0:

~\Anaconda3\lib\site-packages\mxnet\base.py in check_call(ret)
    251     if ret != 0:
--> 252         raise MXNetError(py_str(_LIB.MXGetLastError()))
    253 

MXNetError: Error in operator deepartrainingnetwork0_featureembedder0_squeeze0: [15:53:27] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./matrix_op-inl.h:2178: Check failed: dshape[axes[i]] == 1 (2 vs. 1) cannot select an axis to squeeze out which has size=2 not equal to one

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~\Dropbox\DS\RNN-for-TS\gluonts10-m4_subsets_local\utils_gluonts10_deepar.py in deepar(data, seed, epochs, batches)
     42     # predictor = estimator.train(training_data=dataset.train,
     43     #                             validation_data=dataset.test)
---> 44     predictor = estimator.train(training_data=dataset.train)
     45 
     46     forecast_it, ts_it = make_evaluation_predictions(

~\Anaconda3\lib\site-packages\gluonts\model\estimator.py in train(self, training_data, validation_data)
    221         self, training_data: Dataset, validation_data: Optional[Dataset] = None
    222     ) -> Predictor:
--> 223         return self.train_model(training_data, validation_data).predictor

~\Anaconda3\lib\site-packages\gluonts\model\estimator.py in train_model(self, training_data, validation_data)
    206             input_names=get_hybrid_forward_input_names(trained_net),
    207             train_iter=training_data_loader,
--> 208             validation_iter=validation_data_loader,
    209         )
    210 

~\Anaconda3\lib\site-packages\gluonts\trainer\_base.py in __call__(self, net, input_names, train_iter, validation_iter)
    295                     )
    296 
--> 297                     epoch_loss = loop(epoch_no, train_iter)
    298                     if is_validation_available:
    299                         epoch_loss = loop(

~\Anaconda3\lib\site-packages\gluonts\trainer\_base.py in loop(epoch_no, batch_iter, is_training)
    235 
    236                             with mx.autograd.record():
--> 237                                 output = net(*inputs)
    238 
    239                                 # network can returns several outputs, the first being always the loss

~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in __call__(self, *args)
    538             hook(self, args)
    539 
--> 540         out = self.forward(*args)
    541 
    542         for hook in self._forward_hooks.values():

~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in forward(self, x, *args)
    905             with x.context as ctx:
    906                 if self._active:
--> 907                     return self._call_cached_op(x, *args)
    908 
    909                 try:

~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in _call_cached_op(self, *args)
    803                      for is_arg, i in self._cached_op_args]
    804         except DeferredInitializationError:
--> 805             self._deferred_infer_shape(*args)
    806             cargs = []
    807             for is_arg, i in self._cached_op_args:

~\Anaconda3\lib\site-packages\mxnet\gluon\block.py in _deferred_infer_shape(self, *args)
    791             error_msg = "Deferred initialization failed because shape"\
    792                         " cannot be inferred. {}".format(e)
--> 793             raise ValueError(error_msg)
    794 
    795     def _call_cached_op(self, *args):

ValueError: Deferred initialization failed because shape cannot be inferred. Error in operator deepartrainingnetwork0_featureembedder0_squeeze0: [15:53:27] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./matrix_op-inl.h:2178: Check failed: dshape[axes[i]] == 1 (2 vs. 1) cannot select an axis to squeeze out which has size=2 not equal to one
```
 
Is there any known fix to this problem? Appreciate any help.

**Comment by gjmulder** [comment]
@tm1611 I finally had some opportunity over Christmas to get back to this. Interestingly, I have found that providing the correct start dates for the daily data does provide a noticeable improvement, specifically in MASE which is perhaps more sensitive to seasonality error:

Model|Data Set|Training MASE|Training sMAPE|Testing MASE|Testing sMAPE
-|-|-|-|-|-
DeepAREstimator|m4 daily, mock dates|4.373|37.70 |4.546|41.34
DeepAREstimator|m4 daily, true dates|4.291|36.57|4.304|39.19

(Note that these results are preliminary and represent different model architectures found by HPO, so not as apples-to-apples as your tests).

I suspect that for yearly, quarterly and monthly there's not much in the way of seasonal knowledge transfer between the time series. In contrast, the daily data has multiple seasonalities (weekly, monthly and yearly), so the correct date alignment for daily data may allow it to learn things like weekend and holiday effects, etc.
