### ISSUE TITLE
Incremental Learning

### ISSUE THREAD

**Issue by RXY3832** [awslabs/gluonts#557]
I thought I saw somewhere, that some one was able to re-load weights from a previously trained predictor and create a new model starting from the previously learned weights. One the incremental learning, they set the epoch=1. 

My question is, can someone remind me how that was done? 

Thanks!

**Comment by samosun** [comment]
related to https://github.com/awslabs/gluon-ts/issues/272?

**Comment by lostella** [comment]
This functionality was exposed in #2244 (released with v0.11)
